"""add unique skill name

Revision ID: 45162cb49440
Revises: e6ee24e5ae04
Create Date: 2026-06-01 11:16:39.669111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45162cb49440'
down_revision: Union[str, Sequence[str], None] = 'e6ee24e5ae04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'skills', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skills', type_='unique')
    # ### end Alembic commands ###
